### PR TITLE
allowed "none" and multi-groups

### PR DESCRIPTION
**Pull request by qiyunzhu**
@serenejiang this is the fix we discussed. It allows transform_type = "none" as a string in addition to None. Please see also https://github.com/serenejiang/q2_dsfdr/pull/10

### CODE REVIEW

**Comment by qiyunzhu** [comment]
I am not exactly sure if multi-group KW test would work as anticipated. In Calour this feature is enabled by default and [documented](http://biocore.github.io/calour/generated/calour.analysis.diff_abundance_kw.html#calour.analysis.diff_abundance_kw). However in dsfdr.py, the `filterBH` and `gilbertBH` code blocks seem to be designed for two groups only. Is it advised that the KW method and those two FDR methods should not be used simultaneously? @serenejiang

**Comment by serenejiang** [comment]
Hi, Qiyun. We added filterBH and gilbertBH methods due to reviewer's requests of comparing dsFDR to these two methods (that's why they appeared in the code and are only working for the two-group comparisons). But we showed that dsFDR performs better than these two methods, so you don't need to be worry about using either of filterBH or gilbertBH.

**Comment by serenejiang** [comment]
I vaguely remember that we have two different ways to calculate the test statistics for Kruskal-Wallis test (one is called "Kruwallis" in the statistics.py, and the other called "KruskalH"). I do remember the one being used in the dsfdr code was "Kruwallis", which was simply using the calculation from python package directly, but it was very slow when you need to do permutation on top of Kruskal Wallis test. So even if the Kruskal Wallis works, it might be very slow; you could switch to use "kruskalH" instead.

**Comment by qiyunzhu** [comment]
@serenejiang Thank you for review and explanation!

**Pull request merged**
